apiVersion: v1
kind: BuildConfig
metadata:
  name: jmeter-base
spec:
  output:
    to:
      kind: ImageStreamTag
      name: rhel-jmeter:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: rhel
      uri: https://github.com/domenicbove/jmeter-docker
    type: Git
    contextDir: jmeter-base
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: rhel:7.3
        namespace: openshift
    type: Docker
  triggers:
  - github:
      secret: 1802aa5420b11b2c
    type: GitHub
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
